---
- name: install css/js packages
  become_user: "{{ app_deploy_user }}"
  command: yarn
  args:
    chdir: "{{ app_base_path }}/{{ item.key }}"
  when: item.value.bundle is defined
  with_dict: "{{ apps }}"
  tags:
    - bedita-package

- name: create JS/CSS bundle
  become_user: "{{ app_deploy_user }}"
  command: yarn build
  args:
    chdir: "{{ app_base_path }}/{{ item.key }}"
  when: item.value.bundle is defined
  with_dict: "{{ apps }}"
  tags:
    - bedita-package

- name: create package archive
  become_user: "{{ app_deploy_user }}"
  archive:
    path:
    - "{{ app_base_path }}/{{ item.key }}/*"
    dest: "{{ app_base_path }}/{{ item.key }}-{{ pack_suffix }}.tar.gz"
    exclude_path:
    - "{{ app_base_path }}/{{ item.key }}/.git"
    - "{{ app_base_path }}/{{ item.key }}/logs"
    - "{{ app_base_path }}/{{ item.key }}/node_modules"
    - "{{ app_base_path }}/{{ item.key }}/tests"
    - "{{ app_base_path }}/{{ item.key }}/tmp"
    owner: "{{ app_deploy_user }}"
    format: gz
  with_dict: "{{ apps }}"
  tags:
    - bedita-package

- name: fetch package 
  fetch:
    src: "{{ app_base_path }}/{{ item.key }}-{{ pack_suffix }}.tar.gz"
    dest: "tmp/packages/{{ item.key }}-{{ pack_suffix }}.tar.gz"
    flat: yes
  with_dict: "{{ apps }}"
  tags:
    - bedita-package
