---
- name: clone plugins via git
  git:
    repo: "{{ plugin.value.src }}"
    version: "{{ plugin.value.version }}"
    dest: "{{ app_base_path }}/{{ plugin.value.path }}/plugins/{{ plugin.key }}"
    accept_hostkey: yes
    update: yes
    force: yes

- name: get git hash
  shell: git rev-parse --short HEAD
  args:
    chdir: "{{ app_base_path }}/{{ plugin.value.path }}/plugins/{{ plugin.key }}"
  register: p_commit

- set_fact:
    versions: "{{ versions | combine({plugin.value.path: {'plugins': {plugin.key: {'commit': p_commit.stdout, 'version': plugin.value.version}}}}, recursive=true) }}"
