---
- name: clone plugins via git
  become: yes
  become_user: "{{ app_deploy_user }}"
  git:
    repo: "{{ plugin.value.src }}"
    version: "{{ plugin.value.version }}"
    dest: "{{ app_base_path }}/{{ plugin.value.path }}/plugins/{{ plugin.key }}"
    accept_hostkey: yes
    update: yes
    force: yes
  with_dict: "{{ plugin }}"
  tags: 
    - bedita-apps
