---
- name: ensure $COMPOSER_HOME dir exists
  become: yes
  become_user: root
  file:
    path: "{{ app_composer_path }}"
    state: directory
    owner: "{{ app_deploy_user }}"
    mode: 0755
  with_dict: "{{ apps }}"

- name: set up composer github auth token
  command: "composer global config github-oauth.github.com {{ app_composer_github_token }}"
  when: app_composer_github_token | default("") != ""

- name: ensure app `logs` directory exists
  become: yes
  become_user: root
  file:
    path: "{{ app_logs_path }}/{{ item.key }}"
    state: directory
    owner: "{{ app_deploy_user }}"
    mode: 0755
  with_dict: "{{ apps }}"

- name: ensure app `tmp` directory exists
  become: yes
  become_user: root
  file:
    path: "{{ app_tmp_path }}/{{ item.key }}"
    state: directory
    owner: "{{ app_deploy_user }}"
    mode: 0755
  with_dict: "{{ apps }}"
